#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SurfaceKind {
    Picker,
    Document,
    Utility,
    Prompt,
    Toast,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ChromeVariant {
    FloatingPicker,
    Document,
    Utility,
    Prompt,
    Toast,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SurfaceLifecycle {
    CachedHidden,
    DestroyOnClose,
    RequestResponse,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoundsPolicy {
    CursorMonitor,
    LastMonitor,
    FixedPosition,
    None,
}

#[derive(Clone, Copy, Debug)]
pub struct SurfaceWindow {
    pub label: &'static str,
    pub route: &'static str,
    pub title: &'static str,
    pub kind: SurfaceKind,
    pub chrome: ChromeVariant,
    pub lifecycle: SurfaceLifecycle,
    pub bounds_policy: BoundsPolicy,
    pub capability: &'static str,
    pub width: u32,
    pub height: u32,
    pub min_width: u32,
    pub min_height: u32,
    pub max_width: Option<u32>,
    pub max_height: Option<u32>,
    pub decorations: bool,
    pub transparent: bool,
    pub resizable: bool,
    pub shadow: bool,
    pub skip_taskbar: bool,
    pub always_on_top: bool,
    pub persist_bounds: bool,
    pub persist_by_monitor: bool,
}

pub const MAIN: &str = "main";
pub const SETTINGS: &str = "settings";
pub const AI_OUTPUT: &str = "ai-output";
pub const METADATA: &str = "metadata";
pub const UI_HOST: &str = "ui-host";
pub const NOTIFICATIONS: &str = "notifications";
pub const WHICHKEY: &str = "whichkey";

pub const SURFACES: &[SurfaceWindow] = &[
    SurfaceWindow {
        label: MAIN,
        route: "index.html",
        title: "Copicu",
        kind: SurfaceKind::Picker,
        chrome: ChromeVariant::FloatingPicker,
        lifecycle: SurfaceLifecycle::CachedHidden,
        bounds_policy: BoundsPolicy::CursorMonitor,
        capability: "surface-main",
        width: 820,
        height: 620,
        min_width: 360,
        min_height: 320,
        max_width: None,
        max_height: None,
        decorations: false,
        transparent: false,
        resizable: true,
        shadow: false,
        skip_taskbar: true,
        always_on_top: false,
        persist_bounds: true,
        persist_by_monitor: true,
    },
    SurfaceWindow {
        label: SETTINGS,
        route: "index.html",
        title: "Copicu Settings",
        kind: SurfaceKind::Document,
        chrome: ChromeVariant::Document,
        lifecycle: SurfaceLifecycle::CachedHidden,
        bounds_policy: BoundsPolicy::LastMonitor,
        capability: "surface-settings",
        width: 820,
        height: 620,
        min_width: 680,
        min_height: 460,
        max_width: None,
        max_height: None,
        decorations: false,
        transparent: false,
        resizable: true,
        shadow: false,
        skip_taskbar: false,
        always_on_top: false,
        persist_bounds: true,
        persist_by_monitor: true,
    },
    SurfaceWindow {
        label: AI_OUTPUT,
        route: "index.html",
        title: "Copicu Output",
        kind: SurfaceKind::Document,
        chrome: ChromeVariant::Document,
        lifecycle: SurfaceLifecycle::CachedHidden,
        bounds_policy: BoundsPolicy::LastMonitor,
        capability: "surface-ai-output",
        width: 940,
        height: 680,
        min_width: 680,
        min_height: 460,
        max_width: None,
        max_height: None,
        decorations: false,
        transparent: false,
        resizable: true,
        shadow: false,
        skip_taskbar: false,
        always_on_top: false,
        persist_bounds: true,
        persist_by_monitor: true,
    },
    SurfaceWindow {
        label: METADATA,
        route: "index.html?window=metadata",
        title: "Copicu Metadata",
        kind: SurfaceKind::Utility,
        chrome: ChromeVariant::Utility,
        lifecycle: SurfaceLifecycle::CachedHidden,
        bounds_policy: BoundsPolicy::LastMonitor,
        capability: "surface-metadata",
        width: 620,
        height: 520,
        min_width: 460,
        min_height: 360,
        max_width: None,
        max_height: None,
        decorations: false,
        transparent: false,
        resizable: true,
        shadow: false,
        skip_taskbar: false,
        always_on_top: false,
        persist_bounds: true,
        persist_by_monitor: true,
    },
    SurfaceWindow {
        label: UI_HOST,
        route: "index.html?window=ui-host",
        title: "Copicu",
        kind: SurfaceKind::Prompt,
        chrome: ChromeVariant::Prompt,
        lifecycle: SurfaceLifecycle::RequestResponse,
        bounds_policy: BoundsPolicy::None,
        capability: "surface-ui-host",
        width: 410,
        height: 240,
        min_width: 320,
        min_height: 170,
        max_width: Some(460),
        max_height: Some(240),
        decorations: false,
        transparent: true,
        resizable: false,
        shadow: false,
        skip_taskbar: true,
        always_on_top: true,
        persist_bounds: false,
        persist_by_monitor: false,
    },
    SurfaceWindow {
        label: NOTIFICATIONS,
        route: "index.html",
        title: "Copicu Notifications",
        kind: SurfaceKind::Toast,
        chrome: ChromeVariant::Toast,
        lifecycle: SurfaceLifecycle::CachedHidden,
        bounds_policy: BoundsPolicy::FixedPosition,
        capability: "surface-notifications",
        width: 340,
        height: 430,
        min_width: 340,
        min_height: 430,
        max_width: Some(340),
        max_height: Some(430),
        decorations: false,
        transparent: true,
        resizable: false,
        shadow: false,
        skip_taskbar: true,
        always_on_top: true,
        persist_bounds: false,
        persist_by_monitor: false,
    },
    SurfaceWindow {
        label: WHICHKEY,
        route: "index.html?window=whichkey",
        title: "Copicu WhichKey",
        kind: SurfaceKind::Utility,
        chrome: ChromeVariant::Utility,
        lifecycle: SurfaceLifecycle::DestroyOnClose,
        bounds_policy: BoundsPolicy::FixedPosition,
        capability: "surface-whichkey",
        width: 440,
        height: 260,
        min_width: 320,
        min_height: 160,
        max_width: Some(520),
        max_height: Some(420),
        decorations: false,
        transparent: false,
        resizable: false,
        shadow: false,
        skip_taskbar: true,
        always_on_top: true,
        persist_bounds: false,
        persist_by_monitor: false,
    },
];

pub fn get(label: &str) -> Option<&'static SurfaceWindow> {
    SURFACES.iter().find(|surface| surface.label == label)
}

pub fn require(label: &str) -> Result<&'static SurfaceWindow, String> {
    get(label).ok_or_else(|| format!("unknown surface: {label}"))
}
