param(
  [string] $AppDataDir,
  [int] $RemoteDebugPort = 9335,
  [int] $StartupTimeoutSeconds = 120,
  [switch] $SkipBuild
)

$ErrorActionPreference = "Stop"
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -ErrorAction SilentlyContinue) {
  $PSNativeCommandUseErrorActionPreference = $true
}

function Stop-Tree($ProcessId) {
  $children = Get-CimInstance Win32_Process | Where-Object { $_.ParentProcessId -eq $ProcessId }
  foreach ($child in $children) {
    Stop-Tree $child.ProcessId
  }
  Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue
}

function Get-RepoProcessIds($RepoRoot) {
  $escapedRepoRoot = [regex]::Escape($RepoRoot)
  Get-CimInstance Win32_Process |
    Where-Object {
      $_.Name -ieq "copicu.exe" -or
      ($_.CommandLine -match $escapedRepoRoot -and $_.CommandLine -match "tauri dev|@tauri-apps\\cli\\tauri\.js|cargo(\.exe)?.*run.*copicu")
    } |
    Select-Object -ExpandProperty ProcessId -Unique
}

function Get-CopicuMemorySnapshot($Phase, $RunDir) {
  $processes = @(
    Get-CimInstance Win32_Process |
      Where-Object {
        $_.Name -ieq "copicu.exe" -or
        ($_.Name -ieq "msedgewebview2.exe" -and $_.CommandLine -match "dev\.jpsala\.copicu")
      } |
      ForEach-Object { Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue }
  )
  $private = ($processes | Measure-Object PrivateMemorySize64 -Sum).Sum
  $workingSet = ($processes | Measure-Object WorkingSet64 -Sum).Sum
  $row = [pscustomobject]@{
    phase = $Phase
    at = (Get-Date).ToString("o")
    processCount = $processes.Count
    copicuCount = @($processes | Where-Object ProcessName -eq "copicu").Count
    webviewCount = @($processes | Where-Object ProcessName -eq "msedgewebview2").Count
    privateMb = [math]::Round($private / 1MB, 1)
    workingSetMb = [math]::Round($workingSet / 1MB, 1)
  }
  $csv = Join-Path $RunDir "memory-snapshots.csv"
  if (Test-Path -LiteralPath $csv) {
    $row | Export-Csv -LiteralPath $csv -NoTypeInformation -Append
  } else {
    $row | Export-Csv -LiteralPath $csv -NoTypeInformation
  }
  $row
}

function New-SyntheticLifecycleScripts($ScriptsDir) {
  $aiScriptsDir = Join-Path $ScriptsDir "ai-output"
  $uiScriptsDir = Join-Path $ScriptsDir "ui-host"
  New-Item -ItemType Directory -Force -Path $aiScriptsDir | Out-Null
  New-Item -ItemType Directory -Force -Path $uiScriptsDir | Out-Null

  @'
export default defineAction({
  id: "perf.syntheticMarkdownOutput",
  title: "Perf synthetic markdown output",
  description: "Synthetic lifecycle harness action for AI Output.",
  triggers: ["clipboardChange"],
  input: { source: "clipboard", selection: "none", kinds: ["text"] },
  capabilities: ["ui:markdown-output", "log:write"],
  logging: { name: "perf-synthetic-markdown-output.jsonl", redact: true },
  async run() {
    const markdown = [
      "# COPICU_SYNTH_PERF AI Output",
      "",
      "This is synthetic markdown generated by the lifecycle harness.",
      "",
      "## Measurements",
      "",
      "- Window path: script action -> ui.markdownOutput",
      "- Payload: synthetic only",
      "- Purpose: memory and cached reopen timing",
      "",
      "```ts",
      "await copicu.ui.markdownOutput({ title, markdown });",
      "```",
    ].join("\n");
    await copicu.ui.markdownOutput({
      title: "COPICU_SYNTH_PERF AI Output",
      summary: "Synthetic lifecycle payload.",
      source: "scripts/dev/measure-window-lifecycle.ps1",
      suggestedFileName: "copicu-synth-perf-ai-output",
      markdown,
    });
    await copicu.log.info("synthetic markdown output opened", { markdownLength: markdown.length });
  },
});
'@ | Set-Content -LiteralPath (Join-Path $aiScriptsDir "perf-synthetic-markdown-output.ts") -Encoding UTF8

  @'
export default defineAction({
  id: "perf.syntheticUiHostInput",
  title: "Perf synthetic UI host input",
  description: "Synthetic lifecycle harness action for UI Host.",
  triggers: ["clipboardChange"],
  input: { source: "clipboard", selection: "none", kinds: ["text"] },
  capabilities: ["ui:input", "log:write"],
  logging: { name: "perf-synthetic-ui-host.jsonl", redact: true },
  async run() {
    const value = await copicu.ui.input({
      title: "COPICU_SYNTH_PERF UI Host",
      body: "Synthetic prompt used by the lifecycle harness.",
      placeholder: "synthetic value",
      defaultValue: "COPICU_SYNTH_PERF",
      submitLabel: "Measure",
      cancelLabel: "Cancel",
    });
    await copicu.log.info("synthetic ui host resolved", { hasValue: Boolean(value) });
  },
});
'@ | Set-Content -LiteralPath (Join-Path $uiScriptsDir "perf-synthetic-ui-host.ts") -Encoding UTF8

  [pscustomobject]@{
    Root = $ScriptsDir
    Ai = $aiScriptsDir
    Ui = $uiScriptsDir
  }
}

function Set-SyntheticScriptsSetting($AppDataDir, $ScriptsDir) {
  $dbPath = Join-Path $AppDataDir "copicu.sqlite3"
  if (-not (Test-Path -LiteralPath $dbPath)) {
    return
  }

  $settings = @{
    schemaVersion = 1
    general = @{
      globalShortcut = "Ctrl+Shift+,"
      launchOnStartup = $false
    }
    picker = @{
      hideOnFocusLost = $true
      enterAction = "copy"
    }
    history = @{
      retentionCount = 0
    }
    appearance = @{
      theme = "system"
      themeId = "default"
    }
    scripts = @{
      folderPath = $ScriptsDir
    }
    ai = @{
      enabled = $false
      endpoint = "https://openrouter.ai/api/v1"
      model = "openai/gpt-4.1-mini"
    }
  }
  $settingsJson = ($settings | ConvertTo-Json -Depth 8 -Compress).Replace("'", "''")
  $now = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  $sql = "INSERT INTO app_settings (key, value_json, updated_at_unix_ms) VALUES ('app', '$settingsJson', $now) ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json, updated_at_unix_ms = excluded.updated_at_unix_ms;"
  $sql | sqlite3 $dbPath
  if ($LASTEXITCODE -ne 0) {
    throw "failed to prepare synthetic scripts setting in $dbPath"
  }
}

function Invoke-CdpLifecycleStep($Port, $Step, $RunDir, [switch] $AllowFailure) {
  $nodeScript = @'
const { chromium } = require("@playwright/test");

const port = Number(process.argv[2]);
const step = process.argv[3];
const scriptsDir = process.argv[4];

function now() {
  return Date.now();
}

async function findPage(context, predicate, timeoutMs = 10000) {
  const deadline = now() + timeoutMs;
  while (now() < deadline) {
    for (const page of context.pages()) {
      const ok = await predicate(page).catch(() => false);
      if (ok) return page;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  return null;
}

async function isSettingsPage(page) {
  return page.evaluate(() => document.body.classList.contains("settings-window"));
}

async function isAiOutputPage(page) {
  return page.evaluate(() => document.body.classList.contains("ai-output-window"));
}

async function isUiHostPage(page) {
  return page.evaluate(() => document.body.classList.contains("ui-host-window"));
}

async function runAction(mainPage, actionId) {
  return mainPage.evaluate((id) => window.__TAURI_INTERNALS__.invoke("run_action", {
    request: {
      actionId: id,
      context: {
        trigger: "devRun",
        shortcut: null,
        currentItemId: null,
        selectedItemIds: [],
        view: null,
      },
    },
  }), actionId);
}

function writeSyntheticClipboard(marker) {
  const { execFileSync } = require("child_process");
  execFileSync("cmd.exe", ["/c", "clip"], { input: marker, stdio: ["pipe", "ignore", "ignore"] });
}

async function main() {
  const browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
  const context = browser.contexts()[0];
  const mainPage = await findPage(
    context,
    (page) => page.evaluate(() =>
      Boolean(window.__TAURI_INTERNALS__) &&
      !document.body.classList.contains("settings-window") &&
      !document.body.classList.contains("ai-output-window") &&
      !document.body.classList.contains("ui-host-window")
    ),
    30000,
  );
  if (!mainPage) throw new Error("main page not found");

  const startedAt = now();
  let settingsPage = null;
  let aiOutputPage = null;
  let uiHostPage = null;
  let result = {};

  if (step === "refresh-actions") {
    const refreshResult = await mainPage.evaluate(() => window.__TAURI_INTERNALS__.invoke("refresh_script_action_cache"));
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      scriptCount: Array.isArray(refreshResult) ? refreshResult.length : null,
    };
  } else if (step === "open-settings") {
    await mainPage.evaluate(() => window.__TAURI_INTERNALS__.invoke("open_settings_window"));
    settingsPage = await findPage(context, isSettingsPage, 15000);
    if (!settingsPage) throw new Error("settings page not found after open");
    await settingsPage.waitForSelector(".settings-window-app", { timeout: 15000 });
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      settingsBodyClass: await settingsPage.evaluate(() => document.body.className),
      settingsTextSample: await settingsPage.evaluate(() => document.body.innerText.slice(0, 80)),
    };
  } else if (step === "close-settings") {
    settingsPage = await findPage(context, isSettingsPage, 5000);
    if (!settingsPage) throw new Error("settings page not found before close");
    await settingsPage.evaluate(() => window.__TAURI_INTERNALS__.invoke("close_settings_window"));
    await new Promise((resolve) => setTimeout(resolve, 1000));
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      settingsPageStillInCdp: Boolean(await findPage(context, isSettingsPage, 500)),
    };
  } else if (step === "open-ai-output") {
    writeSyntheticClipboard(`COPICU_SYNTH_PERF_AI_OUTPUT ${Date.now()}`);
    aiOutputPage = await findPage(context, isAiOutputPage, 30000);
    if (!aiOutputPage) throw new Error("ai-output page not found after action");
    await aiOutputPage.waitForSelector(".ai-output-document", { timeout: 15000 });
    writeSyntheticClipboard(`COPICU_SYNTH_PERF_AI_OUTPUT ${Date.now()} READY`);
    await aiOutputPage.waitForFunction(
      () => document.body.innerText.includes("COPICU_SYNTH_PERF AI Output"),
      { timeout: 15000 },
    );
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      trigger: "clipboardChange",
      aiOutputBodyClass: await aiOutputPage.evaluate(() => document.body.className),
      aiOutputTextSample: await aiOutputPage.evaluate(() => document.body.innerText.slice(0, 120)),
    };
  } else if (step === "close-ai-output") {
    aiOutputPage = await findPage(context, isAiOutputPage, 5000);
    if (!aiOutputPage) throw new Error("ai-output page not found before close");
    await aiOutputPage.evaluate(() => window.close());
    await new Promise((resolve) => setTimeout(resolve, 1000));
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      aiOutputPageStillInCdp: Boolean(await findPage(context, isAiOutputPage, 500)),
    };
  } else if (step === "open-ui-host") {
    writeSyntheticClipboard(`COPICU_SYNTH_PERF_UI_HOST ${Date.now()}`);
    uiHostPage = await findPage(context, isUiHostPage, 30000);
    if (!uiHostPage) throw new Error("ui-host page not found after action");
    writeSyntheticClipboard(`COPICU_SYNTH_PERF_UI_HOST ${Date.now()} READY`);
    await uiHostPage.waitForSelector(".ui-host-panel", { timeout: 15000 });
    await uiHostPage.waitForFunction(
      () => document.body.innerText.includes("COPICU_SYNTH_PERF UI Host"),
      { timeout: 15000 },
    );
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      trigger: "clipboardChange",
      uiHostBodyClass: await uiHostPage.evaluate(() => document.body.className),
      uiHostTextSample: await uiHostPage.evaluate(() => document.body.innerText.slice(0, 120)),
    };
  } else if (step === "close-ui-host") {
    uiHostPage = await findPage(context, isUiHostPage, 5000);
    if (!uiHostPage) throw new Error("ui-host page not found before close");
    await uiHostPage.getByRole("button", { name: "Measure" }).click();
    await new Promise((resolve) => setTimeout(resolve, 1000));
    result = {
      step,
      elapsedMs: now() - startedAt,
      pageCount: context.pages().length,
      uiHostPageStillInCdp: Boolean(await findPage(context, isUiHostPage, 500)),
    };
  } else {
    throw new Error(`unknown step: ${step}`);
  }

  await browser.close();
  console.log(JSON.stringify(result));
}

main().catch((error) => {
  console.error(error.stack || String(error));
  process.exit(1);
});
'@

  $output = $nodeScript | node - $Port $Step $scriptsDir 2>&1
  if ($LASTEXITCODE -ne 0) {
    if ($AllowFailure) {
      $row = [pscustomobject]@{
        step = $Step
        status = "failed"
        error = ($output -join "`n")
      }
      $json = $row | ConvertTo-Json -Compress
      $jsonPath = Join-Path $RunDir "lifecycle-events.jsonl"
      Add-Content -LiteralPath $jsonPath -Value $json
      return $row
    }
    throw "CDP lifecycle step failed: $Step`n$($output -join "`n")"
  }
  $jsonLine = $output | Select-Object -Last 1
  $jsonPath = Join-Path $RunDir "lifecycle-events.jsonl"
  Add-Content -LiteralPath $jsonPath -Value $jsonLine
  $jsonLine | ConvertFrom-Json
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$runDir = Join-Path $repoRoot ".codex-run\window-lifecycle\$stamp"
New-Item -ItemType Directory -Force -Path $runDir | Out-Null

if (-not $AppDataDir) {
  $AppDataDir = Join-Path $runDir "app-data"
}
New-Item -ItemType Directory -Force -Path $AppDataDir | Out-Null
$AppDataDir = (Resolve-Path -LiteralPath $AppDataDir).Path
$scriptsDir = Join-Path $runDir "synthetic-scripts"
$scriptDirs = New-SyntheticLifecycleScripts $scriptsDir
Set-SyntheticScriptsSetting $AppDataDir $scriptDirs.Ai

foreach ($processId in @(Get-RepoProcessIds $repoRoot)) {
  if ($processId -ne $PID) {
    Stop-Tree $processId
  }
}
Start-Sleep -Milliseconds 700

if (-not $SkipBuild) {
  Push-Location $repoRoot
  npm run build
  Pop-Location
}

$env:COPICU_APP_DATA_DIR = $AppDataDir
$env:COPICU_SCRIPTS_DIR = $scriptsDir
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$RemoteDebugPort"
$env:VITE_COPICU_RENDERER_DIAGNOSTICS = "errors"

$stdoutLog = Join-Path $runDir "tauri.out.log"
$stderrLog = Join-Path $runDir "tauri.err.log"
$owner = Start-Process `
  -FilePath "npx.cmd" `
  -ArgumentList @("tauri", "dev", "--no-watch", "--config", "src-tauri/tauri.built-dev.conf.json") `
  -WorkingDirectory $repoRoot `
  -RedirectStandardOutput $stdoutLog `
  -RedirectStandardError $stderrLog `
  -WindowStyle Hidden `
  -PassThru

try {
  $deadline = (Get-Date).AddSeconds($StartupTimeoutSeconds)
  do {
    try {
      $targets = Invoke-RestMethod -Uri "http://127.0.0.1:$RemoteDebugPort/json" -TimeoutSec 2
      if ($targets.Count -gt 0) {
        break
      }
    } catch {
      Start-Sleep -Milliseconds 500
    }
  } while ((Get-Date) -lt $deadline)

  if (-not $targets -or $targets.Count -eq 0) {
    throw "WebView2 CDP target did not appear on port $RemoteDebugPort"
  }

  $events = @()
  $snapshots = @()

  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "refresh-actions" $runDir
  $snapshots += Get-CopicuMemorySnapshot "idle-hidden" $runDir
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "open-settings" $runDir
  Start-Sleep -Seconds 2
  $snapshots += Get-CopicuMemorySnapshot "settings-first-open" $runDir
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "close-settings" $runDir
  Start-Sleep -Seconds 2
  $snapshots += Get-CopicuMemorySnapshot "settings-hidden-after-close" $runDir
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "open-settings" $runDir
  Start-Sleep -Seconds 2
  $snapshots += Get-CopicuMemorySnapshot "settings-reopen-cached" $runDir
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "open-ai-output" $runDir
  Start-Sleep -Seconds 2
  $snapshots += Get-CopicuMemorySnapshot "ai-output-first-open" $runDir
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "close-ai-output" $runDir
  Start-Sleep -Seconds 2
  $snapshots += Get-CopicuMemorySnapshot "ai-output-after-close" $runDir
  $aiReopen = Invoke-CdpLifecycleStep $RemoteDebugPort "open-ai-output" $runDir -AllowFailure
  $events += $aiReopen
  if ($aiReopen.status -ne "failed") {
    Start-Sleep -Seconds 2
    $snapshots += Get-CopicuMemorySnapshot "ai-output-reopen" $runDir
  }
  Set-SyntheticScriptsSetting $AppDataDir $scriptDirs.Ui
  $events += Invoke-CdpLifecycleStep $RemoteDebugPort "refresh-actions" $runDir
  $uiHostOpen = Invoke-CdpLifecycleStep $RemoteDebugPort "open-ui-host" $runDir -AllowFailure
  $events += $uiHostOpen
  if ($uiHostOpen.status -ne "failed") {
    Start-Sleep -Seconds 2
    $snapshots += Get-CopicuMemorySnapshot "ui-host-first-open" $runDir
    $events += Invoke-CdpLifecycleStep $RemoteDebugPort "close-ui-host" $runDir
    Start-Sleep -Seconds 2
    $snapshots += Get-CopicuMemorySnapshot "ui-host-hidden-after-resolve" $runDir
    $events += Invoke-CdpLifecycleStep $RemoteDebugPort "open-ui-host" $runDir
    Start-Sleep -Seconds 2
    $snapshots += Get-CopicuMemorySnapshot "ui-host-reopen-cached" $runDir
    $events += Invoke-CdpLifecycleStep $RemoteDebugPort "close-ui-host" $runDir
  }

  [pscustomobject]@{
    runDir = $runDir
    appDataDir = $AppDataDir
    scriptsDir = $scriptDirs.Root
    ownerPid = $owner.Id
    events = $events
    memory = $snapshots
  } | ConvertTo-Json -Depth 8 | Tee-Object -FilePath (Join-Path $runDir "summary.json")
} finally {
  foreach ($processId in @(Get-RepoProcessIds $repoRoot)) {
    if ($processId -ne $PID) {
      Stop-Tree $processId
    }
  }
  Remove-Item Env:\COPICU_APP_DATA_DIR -ErrorAction SilentlyContinue
  Remove-Item Env:\COPICU_SCRIPTS_DIR -ErrorAction SilentlyContinue
  Remove-Item Env:\WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS -ErrorAction SilentlyContinue
  Remove-Item Env:\VITE_COPICU_RENDERER_DIAGNOSTICS -ErrorAction SilentlyContinue
}
